name: "Deploy Hugo to S3"
description: "Build and deploy Hugo static websites to AWS S3"
author: "AlbertMorenoDEV"
branding:
  icon: package
  color: yellow
inputs:
  hugo-version:
    description: "Choose a valid Hugo version"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: false
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: false
  aws-role-to-assume:
    description: "AWS Role to Assume"
    required: false
  aws-region:
    description: "AWS Region"
    required: false
  target:
    description: "A deployment target"
    required: false
    default: ""
  config:
    description: "Config file"
    required: false
    default: ""
  environment:
    description: "environment"
    required: false
    default: ""
  skip-deployment:
    description: "Skip deployment to AWS"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - id: validate-inputs
      run: |
        if [[ "${{ inputs.aws-role-to-assume }}" != "" && "${{ inputs.aws-region }}" == "" ]]; then
          echo "::error::aws-region is required when using OIDC"
          exit 1
        fi
      shell: bash

    - id: install-hugo
      run: |
        set -e

        if [[ "${{ runner.os }}" == "Linux" ]]; then
          HUGO_OS="Linux"
          HUGO_EXTENSION="tar.gz"
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          HUGO_OS="Windows"
          HUGO_EXTENSION="zip"
        elif [[ "${{ runner.os }}" == "macOS" ]]; then
          HUGO_OS="macOS"
          HUGO_EXTENSION="tar.gz"
        fi

        if [[ "${{ runner.arch }}" == "X64" ]]; then
          HUGO_ARCH="64bit"
        elif [[ "${{ runner.arch }}" == "ARM64" ]]; then
          HUGO_ARCH="ARM64"
        fi

        HUGO_DOWNLOAD=hugo_extended_withdeploy_${{ inputs.hugo-version }}_${HUGO_OS}-${HUGO_ARCH}.${HUGO_EXTENSION}
        wget https://github.com/gohugoio/hugo/releases/download/v${{ inputs.hugo-version }}/${HUGO_DOWNLOAD}

        if [[ "${{ runner.os }}" == "Windows" ]]; then
          unzip ${HUGO_DOWNLOAD}
        else
          tar xvzf ${HUGO_DOWNLOAD} hugo
        fi

        mv hugo $HOME/hugo
      shell: bash

    - id: download-themes
      run: |
        set -e
        git submodule init
        git submodule update
      shell: bash

    - id: configure-aws-credentials
      if: "${{ inputs.aws-role-to-assume != '' }}"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - id: hugo-build
      run: |
        set -e
        $HOME/hugo
      shell: bash

    - id: deploy-to-s3
      if: inputs.skip-deployment == 'false'
      run: |
        set -e

        # Initialize an array to hold the Hugo flags.
        HUGO_FLAGS=("--logLevel" "info" "--invalidateCDN" "--maxDeletes" "-1")

        # Add the environment flag if it is provided.
        if [[ "${{ inputs.environment }}" ]]; then
          HUGO_FLAGS+=("--environment" "${{ inputs.environment }}")
        fi

        # Add the config flag if it is provided.
        if [[ "${{ inputs.config }}" ]]; then
          HUGO_FLAGS+=("--config" "${{ inputs.config }}")
        fi

        # Add the target flag if it is provided.
        if [[ "${{ inputs.target }}" ]]; then
          HUGO_FLAGS+=("--target" "${{ inputs.target }}")
        fi

        # Deploy the website.
        $HOME/hugo deploy "${HUGO_FLAGS[@]}"
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      shell: bash
