name: 'Deploy Hugo to S3'
description: 'Build and deploy Hugo static websites to AWS S3'
author: 'AlbertMorenoDEV'
branding:
  icon: package
  color: yellow
inputs:
  hugo-version:
    description: 'Choose a valid Hugo version'
    required: true
  target:
    description: 'A deployment target'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - id: install-hugo
      run: |
        HUGO_DOWNLOAD=hugo_extended_${{ inputs.hugo-version }}_Linux-64bit.tar.gz
        wget https://github.com/gohugoio/hugo/releases/download/v${{ inputs.hugo-version }}/${HUGO_DOWNLOAD}
        tar xvzf ${HUGO_DOWNLOAD} hugo
        mv hugo $HOME/hugo
      shell: bash
    
    - id: download-themes
      run: |
        git submodule init
        git submodule update
      shell: bash
    
    - id: hugo-build
      run: $HOME/hugo -v
      shell: bash
    
    - id: deploy-to-s3
      run: |
        if [[ "${{ inputs.target }}" ]]; then
          $HOME/hugo -v deploy --target=${{ inputs.target }} --invalidateCDN --maxDeletes -1
        else
          $HOME/hugo -v deploy --invalidateCDN --maxDeletes -1
        fi
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
      shell: bash
