name: 'Deploy Hugo to S3'
description: 'Build and deploy Hugo static websites to AWS S3'
author: 'AlbertMorenoDEV'
inputs:
  hugo-version:
    description: 'Choose a valid Hugo version'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Hugo
      run: |
        HUGO_DOWNLOAD=hugo_extended_${{ inputs.hugo-version }}_Linux-64bit.tar.gz
        wget https://github.com/gohugoio/hugo/releases/download/v${{ inputs.hugo-version }}/${HUGO_DOWNLOAD}
        tar xvzf ${HUGO_DOWNLOAD} hugo
        mv hugo $HOME/hugo
    
    - name: Download Theme
      run: |
        git submodule init
        git submodule update
    
    - name: Hugo Build
      run: $HOME/hugo -v
    
    - name: Deploy to S3
      if: github.ref == 'refs/heads/master'
      run: $HOME/hugo -v deploy --invalidateCDN --maxDeletes -1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
